language: node_js
node_js: stable

cache:
  directories:
    - node_modules


install:
  - npm install

before_script:


script:
  - hexo g


after_script:
  - cd ./public
# - echo "rogerabyss.top" > CNAME
  - git init
  - git config user.name "RogerAbyss"
  - git config user.email "roger_ren@qq.com"
  - git add .
  - git commit -m "Travis automatic update"
  - git push --force --quiet "https://${TOKEN}@${REPO}" master:master

branches:
  only:
    - dev

env:
 global:
   - REPO: github.com/RogerAbyss/RogerAbyss.github.io.git